#! /bin/bash


DEFAULT_ZEPHYRPROJECT=~/.zephyrproject/
DEFAULT_ZEPHYRENV=$DEFAULT_ZEPHYRPROJECT/zephyrenv


if [ -n $ZEPHYR_BASE ]; then
	ZEPHYR_BASE=~/.zephyrproject/zephyr
	ZEPHYR_BASE_unset=1
	
	if [[ ! -f $ZEPHYR_BASE/west.yml ]]; then
		mkdir -p ~/.zephyrproject/
		git clone https://github.com/zephyrproject-rtos/zephyr.git $ZEPHYR_BASE
	fi
fi


if [ -n $ZEPHYR_TOOLCHAIN_VARIANT ]; then
	ZEPHYR_TOOLCHAIN_VARIANT=zephyr
	ZEPHYR_TOOLCHAIN_VARIANT_unset=1
fi


if [ -n $ZEPHYR_VENV ]; then
	ZEPHYR_VENV=$DEFAULT_ZEPHYRENV/bin/activate
	ZEPHYR_VENV_unset=1
fi 

deactivate_envs () {

	if [ $ZEPHYR_VENV_unset ]; then
		unset ZEPHYR_VENV 
		unset ZEPHYR_VENV_unset 
	fi

	if [ $ZEPHYR_BASE_unset ]; then
		unset ZEPHYR_BASE
		unset ZEPHYR_BASE_unset 
	fi

	if [ $ZEPHYR_TOOLCHAIN_VARIANT_unset ]; then
		unset ZEPHYR_TOOLCHAIN_VARIANT 
		unset ZEPHYR_TOOLCHAIN_VARIANT_unset 
	fi


	unset -f deactivate_envs
}

if [[ $ZEPHYR_VENV ]]; then
	source $ZEPHYR_VENV

	eval "deactivate_super${$(declare -f deactivate)#deactivate}"	

	deactivate () {

		deactivate_super

		unset -f deactivate_super

		deactivate_envs

	}
else
	echo "zephyr venv is not set. skip venv activation."
	# TODO: set python venv for zephyrproject.
	
	deactivate_envs
fi


unset DEFAULT_ZEPHYRPROJECT
unset DEFAULT_ZEPHYRENV
